language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  secure: JtLoWLPGF6c4DgNRvzGU6GMPc5Y1ghdVr4FxjDMQJwc4VPN4TU3zJjtdUSrBmFDPX9/trg1nEc8nrrs+JcoW4JxHEMDza1bLEd6YmCfI5k9J4SydZYpny3Y5BXpqeRdtoDQCvZQ6wVk9R+honptysKqwrb4ZKuEpnRWW6UlNmlgJiW1alZXhxVPhk8La/h4qtkVf3dhE9XZqzS4UrmdJYif/5BFyrQlBGJtg0lkuTihT3RBJ85xV3ymsGVFYi/8bXlXXWvS410qSdoZTesaD7GXn13dbi/ApNOGiTUg08riXlEf/Alg5e58FfvLNlAH/GS0sXDTJEUAI5eJU5gXPWXvTArWMB2uqkSwMDAMecVQRkNB1e1EDOX7qezhc6qqz93fVmkixi0AWmzdj0C2C/7ceBdcYLGpGauu6sLirLTykY+QkN7MiOcat+QJu+kaUi7I155KDLosGPojM8XXZQDq1hOSJPzmiHeEv9zdkheiN0Ibcj1QJPNRf5B9g9bdLuhNBu+LaRoxFLYjV/7akuAcMEGaF6/LNYH8YJU+Ti/ljq7jX1052hwf1K1TSdKjp/H3E00mAOpI4HimDvYRx4H1WZBupL+MtXsP9VBiCeFoHFU9kFREFEpTXDSvjU4LDMN7ftfqpMv60CqyB3zRPbwuJ1BSJwd006JBtWK37mCM=
install: python setup.py install
script: starred --username maguowei --sort
deploy:
  provider: pypi
  user: maguowei
  password:
    secure: X0Q9rBV65HNYWbqggB7gFpF7KRbEobGAuSX57J1LTM6ukYAYJi5WdFuIs4qNEatLO+JJS86irxS5KOoNZqRhecuC9Qntx07sqa0759ZzjYJpzf1/tmPyc0mOFIDDQp+TGY4WPIEwttB4MhyXRyyYRQNOXA82tgL0LPnGtdD+edHLXNU2Hq4RCVThiapM6Z848qduffwvbocn8CORhsO1AH9M3pFEKr/4GWu65a8FbnA/r4RDwV287lTiAu4sGJv74HwRbqJbLW1C7Y3WGZp2cfKC2e0BI3/4gwNpp6IvEUk4B9soOfrP2ZuIW+AMYiXI9R5nwgwzjp6uk/Z3An2ejDdjoNKW84KKCQmpYBZyxhKZAUBXcLIx4ZtB/96BWW/SiFBIQH5AffryB3e8zecSZuPzya7Ifsou3GrXLGze0Ewi8iCfqXFQ5q09Hia0vm6jkW7Qlul7CtaPGT2h9NDTDWBcXlMP2YBPqnue/F3vD1lvw400/HVwY8F48OH+JK6P6BaACEoaIQj8P6153i7q0Qq3uKr0cNdeWlyNy7TiKyhKBY1KjggkXaumhBmbiISdzqhrv8KcWX+fVPd36yF45jsrBFua6OmoL+hcFM5CA3qV7uqkUpVnYzkxGjxlcWG/6T+B+vT+GT7hpiF6uvAfqxzNBrOkabt8MO18u4g24ac=
  on:
    tags: true
    repo: maguowei/starred
  distributions: sdist bdist_wheel
notifications:
  email: false
  slack:
    secure: P+gYlhDfPcAKl5M9TRF739NaRkYgoQ6u6rJjRghH0H1cWQcRfCHzzbQNxAIcxJqWpBUAFTnZMGl1WdrbuV19n/AIoFX7ZZiV4kqSMYKHUrVfGyD1IBdvsvR7/SoMEWB1I6rlrw8yQyrdHigp6A0yg1zUl706TCEVJKDZuqnqeQHBHfwyxrGX8tmCTiPnw1JJQzzpUyppPrwBTjrurOBwUN79eNm/ONxyZGkhJdYGEkXeLZM7FUPMMushmHjv9DzLfa0zoh0szeqm51kDWbtfnJF/upV4pXv/iVx0PDavJ5pnh5eK5FAQInqcEJxS4/xHQrQiq5AlSs8TzSD9wwWedBwspn9+fe2ebCUdAfRgdxQPpS2xOHcgFKQ3YS+v5JDKfjKKGEOnlvfjtq/KgaBHXzMZPOAzFRQDC0m886E7vuKgeYH7QyflCD3es6k42EmXkMgUKIzMYOtWI2tx78OlZ4T/Tyn98f0/wOJUzKkyqQk6jnV6xcK4nDkF6f4aZm1qgJoauItbex9sLDeC1tuFZ14e94cShnqX7VLOMUkhERJN0bOfUiU3P0JEPJRW/UbAWQC5PtFpngcTNWUzc5Jm84L94s+9d3ADK7Y6rrKanKONIQVtFxWu/wa3+a2MAR73FGnz81OAWSdY0+z6WbpiqhNW9oKL+R/olmuwNh8z/fo=
